artifacts_root: artifacts

data_ingestion:
  root: artifacts/data_ingestion
  raw_data_path: data\archive (2).zip
  extracted_data_path: artifacts/data_ingestion/extracted_data

data_transformation:
  root: artifacts/data_transformation
  full_data_set_path: artifacts/data_ingestion/extracted_data/amazon_alexa.tsv
  tf_idf_vectorizer_path: artifacts/data_transformation/tf_idf_vectorizer
  download_nltk_data: False

model_trainer:
  root: artifacts/model_trainer
  train_x_path: artifacts/data_transformation/train_x.csv
  train_y_path: artifacts\data_transformation\train_y.csv
  model_name: mnb_model

model_eval:
  root: artifacts/model_eval
  model_path: artifacts\model_trainer\mnb_model
  test_x_path: artifacts\data_transformation\test_x.csv
  test_y_path: artifacts\data_transformation\test_y.csv
  metrics_path: artifacts/model_eval/metrics.json
  mlflow_uri: https://dagshub.com/pradeeppvj8/Sentiment-Analysis-Naive-Bayes.mlflow