artifacts_root: artifacts

data_ingestion:
  root: artifacts/data_ingestion
  raw_data_path: data\archive (2).zip
  extracted_data_path: artifacts/data_ingestion/extracted_data

data_transformation:
  root: artifacts/data_transformation
  full_data_set_path: artifacts/data_ingestion/extracted_data/amazon_alexa.tsv
  test_size: 0.2
  tf_idf_vectorizer_path: artifacts/data_transformation/tf_idf_vectorizer
  download_nltk_data: False